"""create oldman notification

Revision ID: 4858aab957ee
Revises:
Create Date: 2026-08-15 03:11:04.717657

Review upgrade() and downgrade() before applying this migration.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4858aab957ee"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("notifications",)
depends_on: str | Sequence[str] | None = "b7c396a46832"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oldman_notification",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.Column("payload", sa.LargeBinary(length=32768), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["recipient_id"], ["oldman_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        info={"oldman_app_label": "notifications", "oldman_managed": True},
    )
    with op.batch_alter_table("oldman_notification", schema=None) as batch_op:
        batch_op.create_index("ix_oldman_notification_recipient_created", ["recipient_id", "created_at", "id"], unique=False)
        batch_op.create_index("ix_oldman_notification_recipient_read_created", ["recipient_id", "read_at", "created_at", "id"], unique=False)

    op.execute(
        "INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('oldman_notification', 'notifications', TRUE, '4858aab957ee')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'oldman_notification' AND app_label = 'notifications'")
    with op.batch_alter_table("oldman_notification", schema=None) as batch_op:
        batch_op.drop_index("ix_oldman_notification_recipient_read_created")
        batch_op.drop_index("ix_oldman_notification_recipient_created")

    op.drop_table("oldman_notification")
    # ### end Alembic commands ###
