"""create oldman role

Revision ID: 261440d5223c
Revises:
Create Date: 2026-09-24 21:44:32.762477

Review upgrade() and downgrade() before applying this migration.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "261440d5223c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("roles",)
depends_on: str | Sequence[str] | None = "b7c396a46832"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oldman_role",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_oldman_role_name"),
        info={"oldman_app_label": "roles", "oldman_managed": True},
        sqlite_autoincrement=True,
    )
    op.create_table(
        "oldman_user_role",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["oldman_role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["oldman_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
        info={"oldman_app_label": "roles", "oldman_managed": True},
    )
    with op.batch_alter_table("oldman_user_role", schema=None) as batch_op:
        batch_op.create_index("ix_oldman_user_role_role_id", ["role_id"], unique=False)

    op.execute(
        "INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('oldman_role', 'roles', TRUE, '261440d5223c')"
    )
    op.execute(
        "INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('oldman_user_role', 'roles', TRUE, '261440d5223c')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'oldman_user_role' AND app_label = 'roles'")
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'oldman_role' AND app_label = 'roles'")
    with op.batch_alter_table("oldman_user_role", schema=None) as batch_op:
        batch_op.drop_index("ix_oldman_user_role_role_id")

    op.drop_table("oldman_user_role")
    op.drop_table("oldman_role")
    # ### end Alembic commands ###
