"""create oldman user

Revision ID: b7c396a46832
Revises:
Create Date: 2026-08-09 23:15:02.327122

Review upgrade() and downgrade() before applying this migration.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b7c396a46832"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("auth",)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oldman_user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=150), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.CheckConstraint("NOT is_superuser OR is_staff", name="ck_oldman_user_superuser_is_staff"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        info={
            "oldman_app_label": "auth",
            "oldman_managed": True,
            "oldman_user_app_label": "auth",
            "oldman_user_core_fields": (
                "id",
                "username",
                "email",
                "password_hash",
                "display_name",
                "is_active",
                "is_staff",
                "is_superuser",
                "last_login_at",
                "created_at",
                "updated_at",
            ),
        },
    )
    with op.batch_alter_table("oldman_user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_oldman_user_is_active"), ["is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_oldman_user_is_staff"), ["is_staff"], unique=False)
        batch_op.create_index(batch_op.f("ix_oldman_user_is_superuser"), ["is_superuser"], unique=False)
        batch_op.create_index(batch_op.f("ix_oldman_user_username"), ["username"], unique=True)

    op.execute(
        "INSERT INTO oldman_schema_registry (table_name, app_label, managed, ownership_revision) VALUES ('oldman_user', 'auth', TRUE, 'b7c396a46832')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM oldman_schema_registry WHERE table_name = 'oldman_user' AND app_label = 'auth'")
    with op.batch_alter_table("oldman_user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oldman_user_username"))
        batch_op.drop_index(batch_op.f("ix_oldman_user_is_superuser"))
        batch_op.drop_index(batch_op.f("ix_oldman_user_is_staff"))
        batch_op.drop_index(batch_op.f("ix_oldman_user_is_active"))

    op.drop_table("oldman_user")
    # ### end Alembic commands ###
